// Generated by https://quicktype.io

import {Product} from "@/common";

export interface SalesforceD2CProduct {
	currency: string;
	id: string;
	image_groups: ImageGroup[];
	long_description: string;
	min_order_quantity: number;
	name: string;
	page_description: string;
	page_title: string;
	price: number;
	primary_category_id: string;
	short_description: string;
	step_quantity: number;
}

export interface ImageGroup {
	_type: string;
	images: Image[];
	view_type: string;
}

export interface Image {
	_type: string;
	alt: string;
	dis_base_link: string;
	link: string;
	title: string;
}






export interface FetchParams {
	url: string,
	method?: 'get' | 'post',
	headers?: {[x: string]: string},
	params?: {[x: string]: string},
	data?: {[x: string]: string}
}

export interface SalesforceD2CCategory {
	id: string;
	name: string;
	slug: string;
	urlName: string;
	children: SalesforceD2CCategory[]
	products: Product[];
	showInMenu: boolean
}

export interface SalesforceD2CMediaItem {
	alternateText: string;
	contentVersionId: null;
	id: string;
	mediaType: string;
	sortOrder: number;
	thumbnailUrl: null;
	title: string;
	url: string;
}

export interface SalesforceD2CMediaGroup {
	developerName: string;
	id: string;
	mediaItems:	SalesforceD2CMediaItem[];
	name: string;
	usageType: string;
}

export interface SalesforceD2CProductResp {
	defaultImage: {
		alternateText: string;
		contentVersionId: string | null;
		id: string;
		mediaType: string;
		sortOrder: number;
		thumbnailUrl: string | null;
		title: string;
		url: string;
	};
	fields: {
		LastModifiedDate: string;
		Image_URL__c: null;
		Image_Height__c: null;
		blng__RevenueRecognitionRule__c: null;
		SBQQ__BillingType__c: null;
		SBQQ__UpgradeTarget__c: null;
		Item_MSRP__c: null;
		Attribute_3__c: null;
		SBQQ__AssetConversion__c: string;
		RevenueInstallmentPeriod: null;
		SBQQ__DescriptionLocked__c: 'true' | 'false';
		SBQQ__NewQuoteGroup__c: 'true' | 'false';
		Approvals__c: string;
		DisplayUrl: null;
		IsDeleted: 'true' | 'false';
		SBQQ__HasConsumptionSchedule__c: 'true' | 'false';
		SBQQ__Optional__c: 'true' | 'false';
		ProductCode: string;
		SBQQ__SubscriptionType__c: string;
		UserRecordAccessId: null;
		SBQQ__Specifications__c: null;
		CanUseRevenueSchedule: 'true' | 'false';
		SBQQ__ChargeType__c: string;
		Model__c: null;
		SBQQ__HidePriceInSearchResults__c: 'true' | 'false';
		EDY_ORGCUSTOM__Old_Name__c: null;
		SBQQ__DefaultPricingTable__c: null;
		Item_Short_Description__c: string;
		SBQQ__PricingGuidance__c: null;
		NumberOfRevenueInstallments: null;
		Warranty__c: null;
		SBQQ__UpgradeCredit__c: null;
		Description: string;
		SBQQ__TaxCode__c: null;
		SBQQ__ExternallyConfigurable__c: 'true' | 'false';
		SBQQ__ProductPictureID__c: null;
		SBQQ__CostEditable__c: 'true' | 'false';
		Image_Width__c: null;
		SBQQ__CustomConfigurationPage__c: null;
		QuantityScheduleType: null;
		Attribute_5__c: null;
		Business_Segment__c: null;
		SBQQ__UpgradeSource__c: null;
		Product_Image__c: string;
		RecordTypeId: null;
		ProductClass: string;
		Guided_Selling__c: null;
		analyticsdemo_batch_id__c: null;
		MayEdit: 'true' | 'false';
		RT_Description__c: string;
		SBQQ__ConfigurationFields__c: null;
		SBQQ__ExcludeFromMaintenance__c: 'true' | 'false';
		SBQQ__DiscountCategory__c: null;
		SBQQ__ConfigurationType__c: null;
		SBQQ__OptionSelectionMethod__c: string;
		SBQQ__CustomConfigurationRequired__c: 'true' | 'false';
		Short_Description__c: string;
		IsLocked: 'true' | 'false';
		ProductImageRelatedList__c: string;
		SystemModstamp: string;
		SBQQ__DefaultQuantity__c: '1.0';
		IsArchived: 'true' | 'false';
		SDO_B2B_Status__c: null;
		Type: null;
		SDO_OMS_Fulfillment_Location__c: null;
		SBQQ__SubscriptionPercent__c: null;
		SBQQ__Component__c: 'true' | 'false';
		SBQQ__TermDiscountSchedule__c: null;
		SBQQ__BlockPricingField__c: string;
		Product_Picture_ID_URL__c: null;
		SBQQ__Taxable__c: 'true' | 'false';
		Available_to_Guest_Users__c: 'true' | 'false';
		Item_Specifications__c: null;
		Family: 'Home Solutions';
		Item_Additional_Details__c: null;
		SBQQ__ConfigurationEvent__c: null;
		SBQQ__GenerateContractedPrice__c: null;
		SBQQ__SubscriptionCategory__c: null;
		SBQQ__DynamicPricingConstraint__c: null;
		SBQQ__ExcludeFromOpportunity__c: 'true' | 'false';
		SBQQ__Hidden__c: 'true' | 'false';
		SBQQ__QuantityEditable__c: 'true' | 'false';
		Power_Source__c: null;
		SBQQ__ConfigurationValidator__c: null;
		Spotter_Configuration__c: null;
		External_ID__c: string;
		SBQQ__NonDiscountable__c: 'true' | 'false';
		CanUseQuantitySchedule: 'true' | 'false';
		SBQQ__ConfigurationFormTitle__c: null;
		SBQQ__BatchQuantity__c: null;
		blng__TaxRule__c: null;
		Name: string;
		TransferRecordMode: null;
		SBQQ__OptionLayout__c: null;
		SBQQ__SubscriptionTerm__c: null;
		CreatedById: string;
		Inventory_Level__c: string;
		SBQQ__IncludeInMaintenance__c: 'true' | 'false';
		SBQQ__PriceEditable__c: 'true' | 'false';
		SBQQ__ReconfigurationDisabled__c: 'true' | 'false';
		Item_Long_Description__c: string;
		SBQQ__AssetAmendmentBehavior__c: string;
		Detail__c: null;
		LastViewedDate: string;
		SBQQ__NonPartnerDiscountable__c: 'true' | 'false';
		Attribute_1__c: null;
		CurrencyIsoCode: string;
		ETA__c: null;
		EDY_ORGCUSTOM__DB__c: 'true' | 'false';
		SBQQ__SubscriptionPricing__c: null;
		Attribute_2__c: null;
		CreatedDate: string;
		Item_Features__c: null;
		SBQQ__SubscriptionTarget__c: null;
		Product_Catalog__c: null;
		SBQQ__ConfiguredCodePattern__c: null;
		IsActive: 'true' | 'false';
		SBQQ__CompoundDiscountRate__c: null;
		SBQQ__CustomerCommunityAvailability__c: null;
		Approval_Threshold__c: string;
		LastReferencedDate: string;
		StockKeepingUnit: string;
		ExternalDataSourceId: null;
		QuantityInstallmentPeriod: null;
		SBQQ__TermDiscountLevel__c: null;
		SBQQ__CostSchedule__c: null;
		SBQQ__ConfigurationFieldSet__c: null;
		SBQQ__ConfiguredDescriptionPattern__c: null;
		SBQQ__DiscountSchedule__c: null;
		SBQQ__SortOrder__c: null;
		SBQQ__UpgradeRatio__c: null;
		SBQQ__QuantityScale__c: null;
		blng__BillingRule__c: null;
		NumberOfQuantityInstallments: null;
		ExternalId: null;
		SBQQ__BillingFrequency__c: null;
		SBQQ__SubscriptionBase__c: string;
		RevenueScheduleType: null;
		Attribute_4__c: string;
		SBQQ__EnableLargeConfiguration__c: 'true' | 'false';
		Image__c: null;
		SBQQ__PricingMethodEditable__c: 'true' | 'false';
		QuantityUnitOfMeasure: null;
		SBQQ__HasConfigurationAttributes__c: 'true' | 'false';
		SBQQ__PricingMethod__c: string;
		GFCI_Safety_Circuit__c: string;
		SBQQ__RenewalProduct__c: null;
		LastModifiedById: string;
		purl__c: string;
		TaxPolicyId: null;
		IsSerialized: 'true' | 'false';
		CPQImage__c: string;
	};
	id: string;
	mediaGroups: SalesforceD2CMediaGroup[];
	primaryProductCategoryPath: {
		path:
			{
				description: null;
				id: string;
				name: string;
				urlName: null
			}[]
	};
	productClass: string;
	purchaseQuantityRule: null;
	urlName: null
}

export interface SalesforceD2CProductsResp{
	products: SalesforceD2CProductResp[]
}

export interface SalesforceD2CCategoryResp {
	categories: SalesforceD2CCategoryResp[]
	showInMenu: 'true' | 'false'
	bannerImage: {
		alternateText:string;
		contentVersionId: string | null;
		id: string;
		mediaType: string;
		sortOrder: number,
		thumbnailUrl: string;
		title: string;
		url: string;
	},
	fields: {
		MayEdit: 'true' | 'false';
		LastModifiedDate: string;
		IsDeleted: 'true' | 'false';
		Description: string | null;
		LastViewedDate: string;
		UserRecordAccessId: string | null;
		External_ID__c: string;
		IsLocked: 'true' | 'false';
		SortOrder: string;
		LastReferencedDate: string;
		CurrencyIsoCode: string;
		CatalogId: string;
		Name: string;
		SystemModstamp: string;
		CreatedById: string;
		NumberOfProducts: string;
		CreatedDate: string;
		IsNavigational: 'true' | 'false';
		Id: string;
		LastModifiedById: string;
		ParentCategoryId: string | null;
},
	id: string;
	mediaGroups: SalesforceD2CMediaGroup[];
	tileImage: {
		alternateText: string;
		contentVersionId: string | null;
		id: string;
		mediaType: string;
		sortOrder: number;
		thumbnailUrl: string | null;
		title: string;
		url: string;
	},
	urlName: null
}

export interface SalesforceD2CSearchResp {
	categories: {
		category: SalesforceD2CCategory,
		children: SalesforceD2CSearchResp[],
		productCount: 13
	},
	correlationId: string;
	facets: [];
	locale: string;
	productsPage: {
		currencyIsoCode: null;
			pageSize: number;
			products: SalesforceD2CProductResp[];
			total: number;
	}
}

export interface SalesforceD2CCategoriesResp {
	productCategories: SalesforceD2CCategoryResp[];
}

export interface SalesforceD2CAxiosResp {
	data: SalesforceD2CSearchResp & SalesforceD2CCategoryResp & SalesforceD2CProductsResp & SalesforceD2CProductResp & SalesforceD2CCategoriesResp
}
